### ISSUE TITLE
jitter labels to avoid overplotting

### ISSUE THREAD

**Issue by gd047** [kassambara/factoextra#1]
Since factoextra uses the ggplot2 plotting system, is there a way to adjust the positioning of text labels (jitter), in order to avoid overlapping?

library("FactoMineR")
library("factoextra")

data(poison)
poison.active <- poison[1:55, 5:15]
res.mca <- MCA(poison.active, graph = FALSE)
fviz_mca_ind(res.mca)

**Comment by kassambara** [comment]
This option will be integrated as soon as possible in the package. Thank you for your suggestion!
AK

**Comment by kassambara** [comment]
# factoextra: Reduce overplotting

The argument **jitter** is now available in factoextra package and documented at : http://www.sthda.com/english/wiki/factoextra-reduce-overplotting-of-points-and-labels-r-software-and-data-mining.

> Install the latest version of factoextra (>= 1.0.3) as follow:  

```
 # install.packages("devtools")
devtools::install_github("kassambara/factoextra")
```

## Compute Multiple Correspondence Analysis

```
library("FactoMineR")
library("factoextra")

# Load data
data(poison)
poison.active <- poison[1:55, 5:15]
# Compute MCA
res.mca <- MCA(poison.active, graph = FALSE)
```

## Default plot

```
# Default plot
fviz_mca_ind(res.mca)
```

![reduce-overplotting-multiple-correspondence-analysis-1](https://cloud.githubusercontent.com/assets/3313355/8510778/b48a9694-22fa-11e5-8921-7bc7d1cc1645.png)

## Use jitter to reduce overplotting

```
Use jitter to reduce overplotting
fviz_mca_ind(res.mca, jitter = list(width = 0.3, height = 0.3))
```

Note that the argument jitter is a list of **width** and **height** parameters:

- width: degree of jitter in x direction
- height: degree of jitter in y direction

![reduce-overplotting-multiple-correspondence-analysis-2](https://cloud.githubusercontent.com/assets/3313355/8510792/2a711e00-22fb-11e5-9ee9-9c281f69ed5a.png)

**Comment by gd047** [comment]
Thank you very much and congratulations on your work!

**Comment by kassambara** [comment]
You’re welcome!
Best wishes,
AK

**Comment by gd047** [comment]
By watching the result again, I think it would be more appropriate if the jittering was made only in the labels and not in the points themselves, because the latter might affect the interpretation. What is your opinion?

**Comment by kassambara** [comment]
At the beginning, I started by making the jitter on the points only; then I observed that, when you have many overlapping points there is a kind of "mismatches" between the points and the labels.  

An intermediate solution is to try to play with the degree of jittering by modifying the width and the height parameters.

**Comment by gd047** [comment]
As an example of what I mean, see on the top left of that image  :  http://imageshack.com/a/img661/3599/mrEc1j.png. 
Individuals 3,5,16 and 20 share the same coordinates. You can see a single point and four distinct labels. The plot was created by FactoMineR::plot.MCA

**Comment by kassambara** [comment]
Ok I can see!! I'll update the package to make the jittering option flexible so that users can choose to jitter the points and/or the labels! Thank you again for your contribution.

**Comment by gd047** [comment]
Not at all! 
 :-) 
Off course, I don't mean to put any pressure on you. Just to make my point clear.
