### ISSUE TITLE
factoextra online documentation

### ISSUE THREAD

**Issue by kassambara** [kassambara/factoextra#12]
Hi @inventionate 

I planned to submit factoextra on CRAN this friday.

To be accepted, CRAN requires "Examples for function" with CPU or elapsed time < 5s

Therefore, I simplified the example section of all the functions and the fviz_*() functions now use ggplot2::stat_ellipse() to draw ellipses.

 I started building an online documentation (http://www.sthda.com/english/rpkgs/factoextra/) so that users can quickly browse documentation and examples.

Have a great day,
AK

**Comment by inventionate** [comment]
Hi @kassambara,

great news! Unfortunately I've at the moment a lot to do and couldn't integrate confidence and overall concentration ellipse. I hope I can do that soon.

Thank you very much for the useful docs and your simplifications and stat_ellipses integration!

Keeping my fingers crossed for a successful and unproblematic CRAN release.

All the best,
Fabian

**Comment by kassambara** [comment]
There is no emergency @inventionate ! I know that you're writing your thesis. 
Oups! I have forgotten this story of confidence ellipse! I can make a suggestion about this!

Best,
AK

**Comment by kassambara** [comment]
Hi @inventionate 

factoextra on CRAN now: https://cran.r-project.org/package=factoextra

Thank you for your great work,
Best,
@lbou

**Comment by inventionate** [comment]
Hi @lbou,

Thank you for your work! Really great!

Very Best,
Fabian
