### ISSUE TITLE
Object of class `dist` as an input to `fviz_nbclust`

### ISSUE THREAD

**Issue by Nowosad** [kassambara/factoextra#15]
Hi!

I've tried to use `fviz_nbclust` function. Based on the help page, it should takes an object x (`matrix`or `data.frame`). However, it's also possible to put there `dist` object and to get different results:

``` R
library('cluster')
library('factoextra')
options(scipen=9)

df <- USArrests
dist_df <- dist(USArrests)

fviz_nbclust(x=df, FUNcluster=pam, method='wss')
fviz_nbclust(x=dist_df, FUNcluster=pam, method='wss')
```

I've checked the source code and found out that inside the function `fviz_nbclust` every `x` object is transformed to `dist` object. Maybe the better way is to transform only `matrix`and `data.frame`object and not transforming `dist`.  Alternatively (but probably not so good) is to forbid `dist` object as an input.

What do you think?

**Comment by kassambara** [comment]
Hi @Nowosad ,


Thank you very much for reporting that. 

yes, every x is transformed to dist for computing 'wss' but we need also the original matrix value to compute FUNcluster, for example "pam".

I think that the best option is to accept only the original matrix value  as an input. I changed the function accordingly.

Best regards,
A.

**Comment by Nowosad** [comment]
Hi @kassambara,
thanks for the answer. Yes, you probably right about the best option.

Best regards,
J.

PS Correct me if I'm wrong - `pam` accept `dist` object also (without having an original matrix). On the other hand `clara` needs to have an original matrix...
