### ISSUE TITLE
Six discrete values limitation with fviz_pca_biplot  

### ISSUE THREAD

**Issue by raz1** [kassambara/factoextra#17]
Hi,

As there is limitation of 6 discrete values with fviz_pca_biplot and I have 20, is there a better/automated way instead of using scale_color_manual(values=c("#999999", "#E69F00", "#56B4E9"...,"#20B2E2")? Furthermore, How can I change the symbols?

Thanks

**Comment by kassambara** [comment]
Now, there is no limitation!
