### ISSUE TITLE
Six discrete values limitation with fviz_pca_biplot 

### ISSUE THREAD

**Issue by raz1** [kassambara/factoextra#18]
Hi,

As there is limitation of 6 discrete values with fviz_pca_biplot and I have 20 Is there a better/automated way instead of using scale_color_manual(values=c("#999999", "#E69F00", "#56B4E9"...,"#20B2E2")?

Thanks

**Comment by kassambara** [comment]
Hi,

I agree with you and I'll automatize this as soon as possible!

Have a great day!!
A>

**Comment by kassambara** [comment]
now, there is no limitation.
