### ISSUE TITLE
Add convex hull to fviz_pca_biplot plot

### ISSUE THREAD

**Issue by lrocax** [kassambara/factoextra#19]
Hi,

How can I add convex hull to fviz_pca_biplot plot?

Thanks.

**Comment by kassambara** [comment]
This is now possible using the argument `ellipse.type = "convex"`.

```r
library("FactoMineR")
res.pca <- PCA(iris[,-5], graph = FALSE)

library("factoextra")
fviz_pca_biplot(res.pca, habillage = iris$Species, label = "var",
                addEllipses = TRUE, ellipse.type = "convex")
```
![rplot02](https://cloud.githubusercontent.com/assets/3313355/21287647/c1df1fc2-c470-11e6-92b6-24f3db477670.png)
