### ISSUE TITLE
Problem Hierarchical clustering with eclust

### ISSUE THREAD

**Issue by gfmartins** [kassambara/factoextra#2]
Hi,

I think i detected a problem in your code, however i don't know how to make submitions in github. I can also be wrong.

in eclust.R:
line 119: res.dist <- get_dist(x, method = hc_metric)
and after that you call line 127: res.hc <- hcut(res.dist, k, hc_func = FUNcluster, hc_method = hc_method )

in hcut.R:
line 63 to 69: you rescale the matrix of distances and calculate again the distances over an already distance matrix
x <- get_dist(x, method = hc_metric)

this makes your eclust function to give results difrent from "hclust"  library.
If you call "hcut function" directly the results are correct!

**Comment by kassambara** [comment]
Hi,

Thank you very much for your excellent point. I modified The code of hcut.R to take into account your input:

* hcut(x, ...): Possible values for x: numeric matrix, numeric data frame or a dissimilarity matrix.

* The R code at line 63 is: if(stand) x <- scale(x). The matrix is rescaled only when stand = TRUE. As the default value of stand = FALSE, rescaling is not computed as you mentioned

* The R code at line 69 was x <- get_dist(x, method = hc_metric). I totally agree with you. To avoid computing distances over an already distance matrix, this line code has been modified as follow: if(!isdiss) x <- get_dist(x, method = hc_metric). So, this line will be executed only when x is not already a dissimilarity matrix.

> Now, the function eclust() should give the same result as the R base function hclust().

Please, install the latest version of factoextra and let me know if it works for you

Thank you again for your contribution,
Best Regards,
A. KASSAMBARA

**Comment by gfmartins** [comment]
It's working.

Thank you for factoextra.
