### ISSUE TITLE
Can't download and install factoextra

### ISSUE THREAD

**Issue by ltomaziu** [kassambara/factoextra#21]
Hello kassambara,

I am using a mac mini computer (macOS Sierra version 10.12) with R (version 3.1.3 (2015-03-09)) and have tried with:

> if(!require(devtools)) install.packages("devtools")
> devtools::install_github("kassambara/factoextra")

And I receive the message:

Downloading github repo kassambara/factoextra@master
Installing factoextra
Skipping 2 packages not available: ggpubr, ggrepel
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  '/private/var/folders/yq/krbpxmw145gg83g7dj3rc_q80000gp/T/RtmpH9nzgY/devtools4bf4bb78637/kassambara-factoextra-cb13301'  \
  --library='/Library/Frameworks/R.framework/Versions/3.1/Resources/library' --install-tests 

ERROR: dependencies ‘ggpubr’, ‘ggrepel’ are not available for package ‘factoextra’
* removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/factoextra’
Error: Command failed (1)

Then when I try to install ggpubr
> if(!require(devtools)) install.packages("devtools")
> devtools::install_github("kassambara/ggpubr")
I get:

ERROR: dependencies ‘ggrepel’, ‘ggsci’ are not available for package ‘ggpubr’
* removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/ggpubr’
Error: Command failed (1)

And when I try with either ggrepel or ggsci
> if(!require(devtools)) install.packages("devtools")
> devtools::install_github("kassambara/ggrepel")
I get:

Downloading github repo kassambara/ggrepel@master
Error in download(dest, src, auth) : client error: (404) Not Found

Do you know why I get these errors and how I can use factoextra?

Regards,
ltomaziu

**Comment by kassambara** [comment]
Hi @ltomaziu ,

This is strange! I didn't have any error on my computer (see session info below). 

Please try the following procedure and let me know if it works:  
   
- Install ggrepel and ggsci first

```r
install.packages(c("ggrepel", "ggsci"))
```

- Install factoextra
   
```r
devtools::install_github("kassambara/ggpubr")
```
Best regards,
A-

<pre>
> session_info()
Session info ----------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.4 (2016-03-10)
 system   x86_64, darwin13.4.0        
 ui       RStudio (0.99.491)          
 language (EN)                        
 collate  fr_FR.UTF-8                 
 tz       Europe/Paris                
 date     2016-11-09                  

Packages --------------------------------------------------------------------------------------------------------------------
 package  * version date       source        
 curl       2.1     2016-09-22 CRAN (R 3.2.5)
 devtools * 1.10.0  2016-01-23 CRAN (R 3.2.3)
 digest     0.6.10  2016-08-02 CRAN (R 3.2.5)
 git2r      0.13.1  2015-12-10 CRAN (R 3.2.3)
 httr       1.2.1   2016-07-03 CRAN (R 3.2.5)
 memoise    1.0.0   2016-01-29 CRAN (R 3.2.3)
 R6         2.1.2   2016-01-26 CRAN (R 3.2.3)
 withr      1.0.1   2016-02-04 CRAN (R 3.2.3)
> 
</pre>

**Comment by ltomaziu** [comment]
Thank you for your fast reply!

I have tried but:

> install.packages(c("ggrepel", "ggsci"))

   packages ‘ggrepel’, ‘ggsci’ are available as source packages but not as binaries

Warning in install.packages :
  packages ‘ggrepel’, ‘ggsci’ are not available (as a binary package for R version 3.1.3)
> 

Maybe there are some problems with mac computers?

Regards,
ltomaziu

**Comment by kassambara** [comment]
I'm on Mac OS X Yosemiteand it works.

Try to install from github as follow:

```r
devtools::install_github("slowkow/ggrepel")
devtools::install_github("road2stat/ggsci")
```

**Comment by ltomaziu** [comment]
Thanks for the reply. However:

> devtools::install_github("slowkow/ggrepel")
Downloading github repo slowkow/ggrepel@master
Installing ggrepel
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  '/private/var/folders/yq/krbpxmw145gg83g7dj3rc_q80000gp/T/RtmpH9nzgY/devtools4bf165061f0/slowkow-ggrepel-7f59da0'  \
  --library='/Library/Frameworks/R.framework/Versions/3.1/Resources/library' --install-tests 

* installing *source* package ‘ggrepel’ ...
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘ggrepel’
* removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/ggrepel’
Error: Command failed (1)

and

> devtools::install_github("road2stat/ggsci")
Downloading github repo road2stat/ggsci@master
Installing ggsci
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  '/private/var/folders/yq/krbpxmw145gg83g7dj3rc_q80000gp/T/RtmpH9nzgY/devtools4bf7f5c92f1/road2stat-ggsci-ec50075'  \
  --library='/Library/Frameworks/R.framework/Versions/3.1/Resources/library' --install-tests 

* installing *source* package ‘ggsci’ ...
** R
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘ggplot2’ 1.0.1 is being loaded, but >= 2.0.0 is required
ERROR: lazy loading failed for package ‘ggsci’
* removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/ggsci’
Error: Command failed (1)
> 

The weird thing is I am not able to update ggplot2. I am working in RStudio and my packages seem up to date when I press the Update button.

**Comment by kassambara** [comment]
It seems that you have a very old version of ggplot2. This should be responsible for the error you got when trying to install factoextra.

Try to update as follow:  

```r
update.packages(oldPkgs = "ggplot2")
```
or

Try to remove ggplot2 and re-install it again:

```r
remove.packages("ggplot2")
install.packages(ggplot2)
```

**Comment by ltomaziu** [comment]
Thank you very much for your help!
I dont understand why I don't get the newest version when I install it. When I try to just update it nothing happens.

> remove.packages("ggplot2")
Removing package from ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library’
(as ‘lib’ is unspecified)
> install.packages(ggplot2)
Error in install.packages : object 'ggplot2' not found
> install.packages("ggplot2")

  There is a binary version available (and will be installed) but the source version is later:
        binary source
ggplot2  1.0.1  2.1.0

trying URL 'http://cran.rstudio.com/bin/macosx/contrib/3.1/ggplot2_1.0.1.tgz'
Content type 'application/x-gzip' length 2662561 bytes (2.5 MB)
opened URL
==================================================
downloaded 2.5 MB


The downloaded binary packages are in
	/var/folders/yq/krbpxmw145gg83g7dj3rc_q80000gp/T//Rtmpvo6oJH/downloaded_packages
>

**Comment by kassambara** [comment]
Hi,

When you tried to install from github, you obtained the error below:  
  
```
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun.
```

I found a solution here: http://apple.stackexchange.com/questions/254380/macos-sierra-invalid-active-developer-path
  

To fix this issue, open Terminal, and run the following:

```
xcode-select --install
```

After installing xcode, try to install the packages from github. For ggplot2 use: devtools::install_github("hadley/ggplot2").

**Comment by ltomaziu** [comment]
Hi,

It works now, thank you very much for your time and help 👍

**Comment by kassambara** [comment]
You're welcome! So we can close this issue
