### ISSUE TITLE
behaviour of the invisible option in fviz_pca()

### ISSUE THREAD

**Issue by ginolhac** [kassambara/factoextra#26]
Hello,

thanks for a very nice package, a great add-on to FactomineR.

In my own data, I have quite a lot of variables and I'd like to make a PCA-biplot where I summarized some variables. It works well, for the plotting, the ideal would be to have:
- points for individuals
- arrows for the quanti.sup only.

so I used the `invisible` option and it doesn't work as I expect.

see a reprex below
```
theme_set(theme_bw())
pca_deca <- PCA(decathlon2, scale.unit = TRUE, graph = FALSE, quanti.sup = 12, quali.sup = c(11, 13))
fviz_pca_biplot(pca_deca, invisible = "quanti.sup")
fviz_pca_biplot(pca_deca)
```
both give the same plots, while I would expect `invisible = "quanti.sup"` to remove **Points**
![image](https://cloud.githubusercontent.com/assets/710181/22652524/16610022-ec87-11e6-9ec7-afbe9e003702.png)

then
```
fviz_pca_biplot(pca_deca, invisible = "var")
```
![image](https://cloud.githubusercontent.com/assets/710181/22652590/4fbca592-ec87-11e6-9511-e5fce284144d.png)

I see only the **quanti.sup**. Shouldn't we keep the individuals and **Points**?
Am  I misinterpreting how invisible works?

```
Session info -------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Europe/Madrid               
 date     2017-02-06  
Packages ---------------------
 factoextra    * 1.0.4      2017-01-09 CRAN (R 3.3.2)                  
 FactoMineR    * 1.34       2016-11-17 CRAN (R 3.3.2)
```

**Comment by kassambara** [comment]
Thank you for reporting this bug!

Should work now!

Best,
/Alboukadel

**Comment by ginolhac** [comment]
awesome!! thanks a lot, works like a charm. Thanks again for such a quick fix.
I have some other requests, but need to figure out if it is a feature request or a bug ;)
