### ISSUE TITLE
Passing ggplot arguments to fviz_mca_biplot

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [kassambara/factoextra#28]
Thanks very much for this work, its super helpful. I am pretty new, so excuse my ignorance, but when I pass some ggplot arguments (for example, renaming the legend using scale_fill_discrete(names = "foobar"), it does not replace the existing legend, but appears in addition to the default (see attached).
<img width="952" alt="screenshot at feb 12 11-21-38" src="https://cloud.githubusercontent.com/assets/7266775/22863884/cabbdb40-f115-11e6-9578-78c018180430.png">

If I give my data frame column a nicely readable name that contains spaces the function chokes:

> fviz_mca_biplot(MCA.object,
+                 invisible=c("ind"),
+                 habillage = 9,
+                 addEllipses = TRUE,
+                 repel = TRUE,
+                 labelsize = 3,
+                 ellipse.level = 0.95, 
+                 title = "test")+
+   theme_minimal()+
+   scale_fill_discrete(name = "Test")
Error in parse(text = x) : <text>:1:9: unexpected symbol
1: Opinion on_courses_needed
            ^

Thanks for any help!

**Comment by kassambara** [comment]
Hi,

The following R code should work.


1) Computing MCA using FactoMineR


```{r}
library("FactoMineR")
data(poison)
res.mca <- MCA(poison.active, graph=FALSE)
```
    
    
2) Visualizing MCA using factoextra. Color individuals by the column "Vomiting" (index = 2).


```{r}
library("factoextra")
fviz_mca_ind(res.mca, label="none", habillage=2,
              addEllipses=TRUE, ellipse.level=0.95
             )
```
    
![rplot](https://cloud.githubusercontent.com/assets/3313355/22864135/0fa04db4-f14c-11e6-9bbf-c1d9a9bbc2ba.png)

3) Changing the legend title to "Vom".


- The easiest solution is to use the argument `legend.title` as follow:

```{r}
fviz_mca_ind(res.mca, label="none", habillage=2,
              addEllipses=TRUE, ellipse.level=0.95,
             legend.title = "Vom"  # Change legend title
             ) + theme_minimal()

```
   
![rplot01](https://cloud.githubusercontent.com/assets/3313355/22864140/25a89d28-f14c-11e6-864b-91ad2539cfe4.png)

   
Note that the functions fviz_XXX() can take additional arguments, such as legend.title, to be passed to the function `ggpubr::ggpar()` for further customization of ggplots. See the online documentation for more information (http://www.sthda.com/english/rpkgs/ggpubr/reference/ggpar.html)


   
If you still want to use the ggplot2 functions for changing the legend title, try this:  
    
    
```{r}
fviz_mca_ind(res.mca, label="none", habillage=2,
              addEllipses=TRUE, ellipse.level=0.95)+
  scale_fill_discrete(name = "Vom")+  # Change leg.title for fill aesthetics
  scale_color_discrete(name = "Vom") # Change leg.title  for color aesthetics
```
     
     
hope that this helps.

Best,
A

**Comment by kassambara** [comment]
Hi @JasonJWilliamsNY ,

Please, let me know if it works so that we can close this issue.

**Comment by JasonJWilliamsNY** [comment]
Hi, 

Adding legend.title as below yields the error: "Error: Don't know how to add RHS to a theme object". As you can see I can pass ggplot arguments (such as ggtitle) without error. I have also tried `scale_fill_discrete(names = "foobar")` which led to the double legend in my original issue. 

`
fviz_mca_biplot(MCA.object,
                invisible=c("ind"),
                habillage = 9,
                addEllipses = TRUE,
                repel = TRUE,
                labelsize = 3,
                legend.title = "TEST"
                ellipse.level = 0.95)+
  theme_minimal()+
  ggtitle(paste("Multiple Correspondence Analysis, question 6, with selected factors n=", dim(tmp[1]), sep = ""), 
          subtitle = "Current bioinformatics teaching \nLevel of bioinformatics training \nSex \nTotal number of undergraduates at institution")`


My Session Info is as below:


`R version 3.3.0 (2016-05-03)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.12.3 (unknown)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] **factoextra_1.0.3** FactoMineR_1.33  pwr_1.2-0        reshape2_1.4.2   dplyr_0.5.0      purrr_0.2.2      readr_1.0.0      tidyr_0.6.1      tibble_1.2      
[10] tidyverse_1.1.1  ggplot2_2.2.0   

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9          plyr_1.8.4           forcats_0.2.0        tools_3.3.0          digest_0.6.12        jsonlite_1.2         lubridate_1.6.0     
 [8] nlme_3.1-127         gtable_0.2.0         lattice_0.20-33      psych_1.6.12         DBI_0.5-1            ggrepel_0.6.5        parallel_3.3.0      
[15] haven_1.0.0          knitr_1.15.1         cluster_2.0.4        stringr_1.1.0        httr_1.2.1           xml2_1.1.1           hms_0.3             
[22] flashClust_1.01-2    scatterplot3d_0.3-38 grid_3.3.0           data.table_1.10.0    R6_2.2.0             readxl_0.1.1         foreign_0.8-66      
[29] modelr_0.1.0         magrittr_1.5         MASS_7.3-45          scales_0.4.1         leaps_3.0            assertthat_0.1       mnormt_1.5-5        
[36] rvest_0.3.2          colorspace_1.3-2     labeling_0.3         stringi_1.1.2        lazyeval_0.2.0       munsell_0.4.3        broom_0.4.1         
> `

Please note, when I upgrade to factoextra_1.0.4 I get other problems... The ellipses, legends,  and other features all go missing as in the attached screen shot:

<img width="703" alt="screenshot at feb 13 16-12-38" src="https://cloud.githubusercontent.com/assets/7266775/22903649/581b3962-f207-11e6-895b-d5fb5e0be0c4.png">

Finally, I also note the examples you gave are all using fca_mc_ind... not sure if this matters. 

Thanks!

**Comment by kassambara** [comment]
Hi,


don't use `invisible = "ind"` because in this case in this case:  individuals are hidden and therefore ellipses and legends are not shown. 

The argument legend.title is available only in the latest version of factoextra.

**Comment by JasonJWilliamsNY** [comment]
Thanks. I have gotten it to work doing this and choosing only to label the variables.
