### ISSUE TITLE
Colour individuals by custom continuous variable

### ISSUE THREAD

**Issue by enricoferrero** [kassambara/factoextra#29]
Hello,

in 'fviz_pca_ind()', 'fviz_mfa_ind()' and similar functions, is it possible to colour individuals using a custom continuous variable?

I'm aware you can do that using one of the presets (e.g.: 'cos2') passed to the 'col.ind' argument and that you can use the 'habillage' argument to colour individuals using a custom factor variable, but neither of those things seems to be doing what I need.

Thank you!

Edit: Alternatively, is there a way to extract the ggplot2 object and edit it?

**Comment by kassambara** [comment]
Should work now:

```r
library(factoextra)
data(iris)
res.pca <- prcomp(iris[, -5],  scale = TRUE)

# Visualize and color by a custom continuous variable
fviz_pca_ind(res.pca, col.ind = iris$Sepal.Length,
           legend.title = "Sepal.Length", 
           gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"))
```

![rplot](https://cloud.githubusercontent.com/assets/3313355/23868132/9ad375da-081e-11e7-9185-f867b53b1ced.png)
