### ISSUE TITLE
fviz_dend doesn't work for diana object

### ISSUE THREAD

**Issue by qfazille** [kassambara/factoextra#30]
Hello,

In fviz_dend file (line 134)
`if(is.na(method)) method <- ""`

But object$method is null when :
- diana class
- hcut with hc_func=diana

This cause error below :
_Error in if (is.na(method)) method <- "" : 
  l'argument est de longueur nulle
De plus : Warning message:
In is.na(method) :
  is.na() appliqué à un objet de type 'NULL' qui n'est ni une liste, ni un vecteur_

Thank you for your work.

**Comment by kassambara** [comment]
Thank you for pointing this out.
Bug fixed now.

To install the latest version, type this:

```r
if(!require(devtools)) install.packages("devtools")
devtools::install_github("kassambara/factoextra")
```
