### ISSUE TITLE
Remove or hide Zeroline on R ggplot2/factoextra plots

### ISSUE THREAD

**Issue by Backpackerice** [kassambara/factoextra#33]
I am using this factoextra package in R to do Correspondent Analysis. 

When I print out the result plot, I can't find the option to hide the x and y zeroline. 
I know that the theme setting is based on ggplot 2. Can anyone help me to figure out how to hide those two lines? 
Please find the code below. 
`fviz_ca_biplot(gen_show_ns.ca,
               geom =c( "text", "point"),
               col.col = "#FF6600",
               col.row = "#336699",
               MAP = "symbiplot",
               labelsize = 5,
               repel = TRUE,
               title = " "
) +
  theme(axis.line=element_blank(),
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        legend.position="none",
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        plot.background=element_blank())})`

And my current output looks like this below: 
https://i.stack.imgur.com/nJLO4.png

Any suggestion helps! Thanks so much

**Comment by kassambara** [comment]
Hi,

Those two lines are not the standard ggplot2 axis lines. So they can't be removed using `theme()`.

To remove them, use the argument **axes.linetype = "blank"** as follow:

```r
fviz_ca_biplot(gen_show_ns.ca, axes.linetype = "blank")
```

kindly confirm that this option works for you.

**Comment by Backpackerice** [comment]
Hi Kassambara,

This totally helps! Thank you so much!

**Comment by kassambara** [comment]
Great, so we can close this issue
