### ISSUE TITLE
fviz_pca_biplot - invisible = "var" Error

### ISSUE THREAD

**Issue by Brizzl** [kassambara/factoextra#35]
While trying to use the **fviz_pca_biplot** with the parameter **invisible = "var**" not only the var became invisible but the whole biplot disappeared/turned invisible, therefore not usable for me at the moment.

**Comment by kassambara** [comment]
Hi,

Please, make sure that you have the latest developmental version of factoextra and ggpubr. You can install them as follow:

```r
if(!require(devtools)) install.packages("devtools")
devtools::install_github("kassambara/ggpubr")
devtools::install_github("kassambara/factoextra")
```

Please, let me know if it works, thanks.

**Comment by Brizzl** [comment]
Yes, thank you the ggpubr did make the difference!
