### ISSUE TITLE
3d plots for PCA

### ISSUE THREAD

**Issue by kickbox** [kassambara/factoextra#40]
Is there an option to plot the PCA components in 3D?

**Comment by kassambara** [comment]
This option is not available in the current release. You can extract the coordinate for individuals/variables and then follow our tutorials at: [3D Graphics](http://www.sthda.com/english/wiki/3d-graphics)

**Comment by kickbox** [comment]
Thanks. Can you let me know how I can extract the co-ordinates please?

**Comment by inventionate** [comment]
If you're using FactoMineR you can access coordinates easily (both, variables and individuals). Furthermore, you can use the get functions of factoextra:

```R
library(FactoMineR)
library(factoextra)

data(wine)

res_pca <- PCA(wine[,3:7], graph = FALSE)

# Opt. 1: FactoMineR results

res_pca$var$coord

res_pca$ind$coord

# Opt. 2: factoextra get functions

res_pca_var <- get_pca(res_pca, element = "var")

res_pca_var$coord

res_pca_ind <- get_pca(res_pca, element = "ind")

res_pca_ind$coord
```

More examples can be found through the delivered link above.

**Comment by kickbox** [comment]
Thanks for this. I was able to extract the values and plot in 3D interactive scatter plot using plotly as below.

```
plot_ly( x = res.pca$ind$coord[,1], y = res.pca$ind$coord[,2], z=res.pca$ind$coord[,3],
        color = train$era)
```

**Comment by kassambara** [comment]
Great, so we can close this issue! Thanks @inventionate

**Comment by krushnach80** [comment]
![41416_2019_404_Fig2_HTML](https://user-images.githubusercontent.com/8524258/178687046-dcc23364-1487-42f5-b511-f5a6cbfcdf4f.jpg)


How do I label this as shown in this fig

my code

```
res.pca <- PCA(t(data),ncp = 10, graph = FALSE)

res.hcpc <- HCPC(res.pca, graph = FALSE)

fviz_dend(res.hcpc, 
          cex = 0.7,                     # Label size
          palette = "jco",               # Color palette see ?ggpubr::ggpar
          rect = TRUE, rect_fill = TRUE, # Add rectangle around groups
          rect_border = "jco",           # Rectangle color
          labels_track_height = 0.8      # Augment the room for labels
)

tiff("plot.tiff",width=3000,height=1856,res=600)
plot(res.hcpc, choice = "3D.map",ind.names=TRUE,cex.axis=3.5,cex.symbols=3.5,xlab="",ylab="")
dev.off()
```

Where can I provide my metadata information so that I can show the same in my 3d plot
