### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by stanleesocca** [kassambara/factoextra#45]
@kassambara @inventionate 

I still can't install factoextra on my PC after trying several means but to no avail. the resulting command prompt it gives each time i try installing on my R studio v.3.3.2 is as followed:

_if(!require(devtools)) install.packages("devtools")
devtools::install_github("kassambara/factoextra")
Downloading GitHub repo kassambara/factoextra@master
from URL https://api.github.com/repos/kassambara/factoextra/zipball/master
Installing factoextra
Downloading GitHub repo kassambara/ggpubr@master
from URL https://api.github.com/repos/kassambara/ggpubr/zipball/master
Installing ggpubr
"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/bright/AppData/Local/Temp/RtmpQzYpWA/devtools19c875f292c/kassambara-ggpubr-5b6e6b2"  \
  --library="C:/Users/bright/Documents/R/win-library/3.3" --install-tests 

* installing *source* package 'ggpubr' ...
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'rlang'
ERROR: lazy loading failed for package 'ggpubr'
* removing 'C:/Users/bright/Documents/R/win-library/3.3/ggpubr'
* restoring previous 'C:/Users/bright/Documents/R/win-library/3.3/ggpubr'
Error: Command failed (1)_

how do i get this done as I find this package really interesting and catchy. I don't whether you can be of help as I need this packages for my thesis analysis.  

Thanks in anticipation.

**Comment by kassambara** [comment]
Hi,

Try this:

- First install rlang as follow:

```r
install.packages("rlang",type="win.binary") 
```

- Then install the latest developmental version of ggpubr and factoextra as follow:

```r
devtools::install_github("kassambara/ggpubr")
devtools::install_github("kassambara/factoextra")
```

kindly confirm that it works so that we can close the issue.

Thanks

**Comment by stanleesocca** [comment]
thanks for the quick response. i installed the factoextra package but couldn't get to installed the ggpubr using the script you provided. i already have the ggpubr pre-installed before now and that perhaps helped in smoothly installing factoextra.
However, trying to run an example using one of the dataset from factoMineR and factoextra resulted in me getting this feedback:
Error in fetch(key) : 
  lazy-load database 'C:/Users/bright/Documents/R/win-library/3.3/FactoMineR/help/FactoMineR.rdb' is corrupt
i don't know what resulted to it. I wouldn't mind if you can help on that.

**Comment by michael6010** [comment]
Hi,
the installation of the factoextra package was a success.
Thanks

**Comment by DimitriosNtak** [comment]
> install.packages("rlang",type="win.binary")

a

**Comment by mcapurso** [comment]
Installation success !!! Thank you

**Comment by ashleymaeconard** [comment]
> > install.packages("rlang",type="win.binary")
> 
> a

sadly this only works with Windows

**Comment by mina-malvandy** [comment]
Hi,

Still I can not install the package in Linux.
