### ISSUE TITLE
Problem visualize clustering results(dbscan) with outliers.

### ISSUE THREAD

**Issue by bdboy** [kassambara/factoextra#5]
Returns: "Unknown parameters: shape"

This is because there is a problem in .addoutliers function.

in fviz_cluster.R:
line 581: size = labelsize, vjust = -0.7, color = outlier.color, shape = outlier.shape)

If you remove the "shape = outlier.shape" it operates normally.

Example:

library(dbscan)
scaled_usa <- scale(USArrests)
fit <- dbscan(scaled_usa, eps=1.24, minPts=NCOL(scaled_usa) + 1)
fviz_cluster(fit, data=scaled_usa)
Error: Unknown parameters: shape

Thank you for factoextra.

**Comment by kassambara** [comment]
The unknown parameter shape has been know removed from geom_text.

Thank you for your contribution...

Best Regards,
A. kassambara

**Comment by bdboy** [comment]
I have been useful to your solution.
And, thanks to the quick patch.

Best Regards,
Choonghyun Ryu
