### ISSUE TITLE
Is it possible to overplot/superimpose fviz_mca_biplot plots?

### ISSUE THREAD

**Issue by jaydautcher** [kassambara/factoextra#6]
Is it possible to overplot/superimpose fviz_mca_biplot plots? if so, how? The `par(new=T)` convention I've seen for overplotting isn't working for me. I am trying to create overplots in jupyter notebooks running R kernel. also, I'm new to github, not sure if this counts as an 'issue'; its more a question. Apologies if this is the wrong forum to ask this.

**Comment by inventionate** [comment]
Since I don't know what you want to superimpose, this discussion may helps you: http://stackoverflow.com/questions/13487625/overlaying-two-graphs-using-ggplot2-in-r#13488046 

In general, factoextra based on ggplot2. So I would recommend to add additional data as ggplo2 objects (geoms).

**Comment by jaydautcher** [comment]
thank you for the reply. regarding what I wanted to superimpose: in R base plotting i can run plot();par(new=T);plot();par(new=T);plot() and 3 plots will be generated, all superimposed. running a series of fviz_mca_biplot() plots with par(new=T) between them [perhaps each shows a different set of individuals selected, with jitter] generates 3 separate plots, not superimposed. As you suggest, given that factoextra is based on ggplot2, treating layers as ggplot2 objects should be a good direction for me to go.

**Comment by inventionate** [comment]
You're very welcome. If you want to highlight (colour) groups of individuals of the same data frame, you can use `hagbillage` to identify them. In this way, you can also plot concentration ellipses for each group  (`addEllipses = TRUE`). The most important part to do this – or any other ggplot2 related thing –  is data preparation. E.g., there have to be a variable to group individuals. `?fviz_mca` shows some rudimentary examples. Good luck!
