### ISSUE TITLE
unable to install ggpubr

### ISSUE THREAD

**Issue by ggsap** [kassambara/factoextra#65]
Dear kassambara,

I am trying to install your nice package but I keep getting an error. I have installed rlang as suggested in other posts and it installed succesfully. However, R still fails to install ggpubr. My R version is 3.1.2. Here's the error I get:

Installing package into ‘C:/Users/GerardS/Documents/R/win-library/3.1’
(as ‘lib’ is unspecified)
* installing *source* package 'ggpubr' ...
** package 'ggpubr' successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Warning: package 'magrittr' was built under R version 3.1.3
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace 'dplyr' 0.4.3 is being loaded, but >= 0.7.1 is required
ERROR: lazy loading failed for package 'ggpubr'
* removing 'C:/Users/GerardS/Documents/R/win-library/3.1/ggpubr'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-31~1.2/bin/i386/R" CMD INSTALL -l "C:\Users\GerardS\Documents\R\win-library\3.1" "C:/Users/GerardS/Downloads/ggpubr_0.1.6.tar.gz"' had status 1
Warning in install.packages :
  installation of package ‘C:/Users/GerardS/Downloads/ggpubr_0.1.6.tar.gz’ had non-zero exit status

**Comment by kassambara** [comment]
Hi, you have a very old version of dplyr (v0.4.3).  Please re-install dplyr version >= 0.7.1

**Comment by ggsap** [comment]
Thank you very much for your help, I was able to resolve it following your advise.

**Comment by bulattoolpix** [comment]
And after all do not forget to reload the enviroment.

**Comment by mas192** [comment]
Hey Kassambara, I really would like to use your library but I am having this error
"Warning in install.packages :
  package ‘/Users/MIRRACLE/Google Drive (samjoshva.b@gmail.com)/R/dplyr_0.7.5.tgz’ is not available (for R version 3.1.2)"

How can I override this?

**Comment by mas192** [comment]
Cause from what I believe I need this version for ggpubr to successfully install right?
this is the error, I got while trying to install ggpubr 
"Downloading github repo kassambara/ggpubr@master
Installing ggpubr
Skipping 5 packages not available: cowplot, ggrepel, ggsci, ggsignif, purrr
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  '/private/var/folders/vv/4kl2702n153fb1z8bv3y7plh0000gn/T/Rtmp6PUTuY/devtools4d29529bd7da/kassambara-ggpubr-d6e249e'  \
  --library='/Library/Frameworks/R.framework/Versions/3.1/Resources/library' --install-tests 

ERROR: dependencies ‘ggrepel’, ‘ggsci’, ‘purrr’, ‘cowplot’, ‘ggsignif’ are not available for package ‘ggpubr’
* removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/ggpubr’
Error: Command failed (1)
> library(ggpubr)
Error in library(ggpubr) : there is no package called ‘ggpubr’"

**Comment by mas192** [comment]
Sorry for multiple commands, I believe I fixed it

**Comment by kassambara** [comment]
Hi, how did you fixe it? by re-installing manually all the dependencies?

**Comment by mas192** [comment]
First I updated my R to 3.50 and r studio 1.1.453 on Mac and then
reinstalled devtool, dplyr and that help fix to install ggpubr.
I have to check if it will work in my PC. I'll keep.you posted.

One quick question how can I keep plots assigned to a colour palette and
just make my error bar black and white or vice versa.

Thanks you so much for this package.

Cheers

**Comment by kassambara** [comment]
Thank you for your answer, so we can close this issue.

Your last question is about ggpubr, so please follow this link: https://github.com/kassambara/ggpubr/issues/92

**Comment by ac10-ui** [comment]
Hi kassambara,

I was wondering if you could please help in resolving isssue with installing "ggpubr" package on windows 10.
**Following are the error lines that I am getting:**
install.packages("ggpubr")
Installing package into ‘\\Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
Warning in install.packages :
  'lib = "\\Documents/R/win-library/3.6"' is not writable
also installing the dependency ‘ggsignif’


  There are binary versions available but the source versions are later:
         binary source needs_compilation
ggsignif  0.5.0  0.6.0             FALSE
ggpubr    0.2.1  0.2.2             FALSE

installing the source packages ‘ggsignif’, ‘ggpubr’

trying URL 'https://cran.rstudio.com/src/contrib/ggsignif_0.6.0.tar.gz'
Content type 'application/x-gzip' length 110226 bytes (107 KB)
downloaded 107 KB

trying URL 'https://cran.rstudio.com/src/contrib/ggpubr_0.2.2.tar.gz'
Content type 'application/x-gzip' length 2662167 bytes (2.5 MB)
downloaded 2.5 MB

* installing *source* package 'ggsignif' ...
** package 'ggsignif' successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
Warning in file.create(to[okay]) :
  cannot create file '\Documents/R/win-library/3.6/00LOCK-ggsignif/00new/ggsignif/doc/intro.R', reason 'No such file or directory'
Warning in file.create(to[okay]) :
  cannot create file '\Documents/R/win-library/3.6/00LOCK-ggsignif/00new/ggsignif/doc/intro.Rmd', reason 'No such file or directory'
Warning in file.create(to[okay]) :
  cannot create file '\Documents/R/win-library/3.6/00LOCK-ggsignif/00new/ggsignif/doc/intro.html', reason 'No such file or directory'
** byte-compile and prepare package for lazy loading
Error in findpack(package, lib.loc) : 
  there is no package called 'ggsignif'
Calls: <Anonymous> -> findpack
Execution halted
ERROR: lazy loading failed for package 'ggsignif'
* removing '\\Documents/R/win-library/3.6/ggsignif'
Warning in install.packages :
  installation of package ‘ggsignif’ had non-zero exit status
ERROR: failed to lock directory '\\Documents/R/win-library/3.6' for modifying
Try removing '\\Documents/R/win-library/3.6/00LOCK-ggpubr'
Warning in install.packages :
  installation of package ‘ggpubr’ had non-zero exit status

I would really appreciate your help on this. Thanks in advance

**Comment by kassambara** [comment]
try this:

```r
install.packages("ggsignif", type="win.binary") 
install.packages("ggpubr", type="win.binary") 
```

**Comment by ac10-ui** [comment]
Hi kassambara,
Thanks for quick reply. I tried your commands but it showed following error:
> install.packages("ggpubr", type="win.binary") 
Installing package into ‘\\Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
Warning in install.packages :
  'lib = "\\Documents/R/win-library/3.6"' is not writable
Error in install.packages : unable to install packages

Regards
Ac

**Comment by Ratheesh-kv** [comment]
Dear Kassambara,
I like your package ggpubr very much and I had used earlier to make some plots. But unfortunately I am anable to load this package now and getting an error message. I really stuck with this issue. So, it will be a great help if you could check this issue please. I use the R studio version 1.1.463

> install.packages("ggpubr")
Installing package into ‘C:/Users/Ratheeshkv/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
       binary source needs_compilation
ggpubr  0.2.5  0.3.0             FALSE

installing the source package ‘ggpubr’

trying URL 'https://cran.rstudio.com/src/contrib/ggpubr_0.3.0.tar.gz'
Content type 'application/x-gzip' length 2671845 bytes (2.5 MB)
downloaded 2.5 MB

* installing *source* package 'ggpubr' ...
** package 'ggpubr' successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Warning: package 'ggplot2' was built under R version 3.5.3
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'car'
ERROR: lazy loading failed for package 'ggpubr'
* removing 'C:/Users/Ratheeshkv/Documents/R/win-library/3.5/ggpubr'
* restoring previous 'C:/Users/Ratheeshkv/Documents/R/win-library/3.5/ggpubr'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘ggpubr’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\Ratheeshkv\AppData\Local\Temp\RtmpSgMUVp\downloaded_packages’

> library("ggpubr")
Error: package or namespace load failed for ‘ggpubr’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘car’

Thanks
Ratheesh

**Comment by kassambara** [comment]
please re-start your R session and try this:


```r
install.packages("car")
install.packages("rstatix")
install.packages("ggpubr")
```

**Comment by Ratheesh-kv** [comment]
Hi Kassambara,
Thanks very much for your quick reply. However, I am still unable to load those packages and getting error messages.
> install.packages("car")
Installing package into ‘C:/Users/Ratheeshkv/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
  dependency ‘pbkrtest’ is not available

  There is a binary version available but the source version is later:
    binary source needs_compilation
car  3.0-7  3.0-8             FALSE

installing the source package ‘car’

trying URL 'https://cran.rstudio.com/src/contrib/car_3.0-8.tar.gz'
Content type 'application/x-gzip' length 499932 bytes (488 KB)
downloaded 488 KB

ERROR: dependency 'pbkrtest' is not available for package 'car'
* removing 'C:/Users/Ratheeshkv/Documents/R/win-library/3.5/car'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘car’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\Ratheeshkv\AppData\Local\Temp\RtmpIVtIkr\downloaded_packages’
> install.packages("rstatix")
Installing package into ‘C:/Users/Ratheeshkv/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
  dependency ‘pbkrtest’ is not available
also installing the dependency ‘car’


  There are binary versions available but the source versions are later:
        binary source needs_compilation
car      3.0-7  3.0-8             FALSE
rstatix  0.4.0  0.5.0             FALSE

installing the source packages ‘car’, ‘rstatix’

trying URL 'https://cran.rstudio.com/src/contrib/car_3.0-8.tar.gz'
Content type 'application/x-gzip' length 499932 bytes (488 KB)
downloaded 488 KB

trying URL 'https://cran.rstudio.com/src/contrib/rstatix_0.5.0.tar.gz'
Content type 'application/x-gzip' length 391492 bytes (382 KB)
downloaded 382 KB

ERROR: dependency 'pbkrtest' is not available for package 'car'
* removing 'C:/Users/Ratheeshkv/Documents/R/win-library/3.5/car'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘car’ had non-zero exit status
ERROR: dependency 'car' is not available for package 'rstatix'
* removing 'C:/Users/Ratheeshkv/Documents/R/win-library/3.5/rstatix'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘rstatix’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\Ratheeshkv\AppData\Local\Temp\RtmpIVtIkr\downloaded_packages’
Thanks
Ratheesh

**Comment by kassambara** [comment]
Does trying to install pbkrtest works?

**Comment by cfritsch10** [comment]
Hello. I am still having a similar issue to the above where a package 'zip' is required to run ggpubr. Even after updating R to 4.0.2, updating all packages and installing package 'zip' I cannot run ggpubr.

R version 4.0.2 (2020-06-22) -- "Taking Off Again"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> update.packages()
data.table :
 Version 1.12.8 installed in /Library/Frameworks/R.framework/Versions/4.0/Resources/library 
 Version 1.13.0 available at https://cran.mirror.ac.za
Update? (Yes/no/cancel) Y
deldir :
 Version 0.1-25 installed in /Library/Frameworks/R.framework/Versions/4.0/Resources/library 
 Version 0.1-28 available at https://cran.mirror.ac.za
Update? (Yes/no/cancel) Y
dplyr :
 Version 1.0.0 installed in /Library/Frameworks/R.framework/Versions/4.0/Resources/library 
 Version 1.0.1 available at https://cran.mirror.ac.za
Update? (Yes/no/cancel) Y
epiR :
 Version 1.0-14 installed in /Library/Frameworks/R.framework/Versions/4.0/Resources/library 
 Version 1.0-15 available at https://cran.mirror.ac.za
Update? (Yes/no/cancel) Y
expm :
 Version 0.999-4 installed in /Library/Frameworks/R.framework/Versions/4.0/Resources/library 
 Version 0.999-5 available at https://cran.mirror.ac.za
Update? (Yes/no/cancel) Y
httr :
 Version 1.4.1 installed in /Library/Frameworks/R.framework/Versions/4.0/Resources/library 
 Version 1.4.2 available at https://cran.mirror.ac.za
Update? (Yes/no/cancel) Y
jsonlite :
 Version 1.6.1 installed in /Library/Frameworks/R.framework/Versions/4.0/Resources/library 
 Version 1.7.0 available at https://cran.mirror.ac.za
Update? (Yes/no/cancel) Y
openssl :
 Version 1.4.1 installed in /Library/Frameworks/R.framework/Versions/4.0/Resources/library 
 Version 1.4.2 available at https://cran.mirror.ac.za
Update? (Yes/no/cancel) Y
pillar :
 Version 1.4.4 installed in /Library/Frameworks/R.framework/Versions/4.0/Resources/library 
 Version 1.4.6 available at https://cran.mirror.ac.za
Update? (Yes/no/cancel) Y
pkgbuild :
 Version 1.0.8 installed in /Library/Frameworks/R.framework/Versions/4.0/Resources/library 
 Version 1.1.0 available at https://cran.mirror.ac.za
Update? (Yes/no/cancel) Y
processx :
 Version 3.4.2 installed in /Library/Frameworks/R.framework/Versions/4.0/Resources/library 
 Version 3.4.3 available at https://cran.mirror.ac.za
Update? (Yes/no/cancel) Y
ps :
 Version 1.3.3 installed in /Library/Frameworks/R.framework/Versions/4.0/Resources/library 
 Version 1.3.4 available at https://cran.mirror.ac.za
Update? (Yes/no/cancel) Y
raster :
 Version 3.1-5 installed in /Library/Frameworks/R.framework/Versions/4.0/Resources/library 
 Version 3.3-13 available at https://cran.mirror.ac.za
Update? (Yes/no/cancel) Y
Rcpp :
 Version 1.0.4.6 installed in /Library/Frameworks/R.framework/Versions/4.0/Resources/library 
 Version 1.0.5 available at https://cran.mirror.ac.za
Update? (Yes/no/cancel) Y
RcppArmadillo :
 Version 0.9.880.1.0 installed in /Library/Frameworks/R.framework/Versions/4.0/Resources/library 
 Version 0.9.900.2.0 available at https://cran.mirror.ac.za
Update? (Yes/no/cancel) Y
rgdal :
 Version 1.5-10 installed in /Library/Frameworks/R.framework/Versions/4.0/Resources/library 
 Version 1.5-16 available at https://cran.mirror.ac.za
Update? (Yes/no/cancel) Y
rlang :
 Version 0.4.6 installed in /Library/Frameworks/R.framework/Versions/4.0/Resources/library 
 Version 0.4.7 available at https://cran.mirror.ac.za
Update? (Yes/no/cancel) Y
survival :
 Version 3.1-12 installed in /Library/Frameworks/R.framework/Versions/4.0/Resources/library 
 Version 3.2-3 available at https://cran.mirror.ac.za
Update? (Yes/no/cancel) Y
sys :
 Version 3.3 installed in /Library/Frameworks/R.framework/Versions/4.0/Resources/library 
 Version 3.4 available at https://cran.mirror.ac.za
Update? (Yes/no/cancel) Y
tibble :
 Version 3.0.1 installed in /Library/Frameworks/R.framework/Versions/4.0/Resources/library 
 Version 3.0.3 available at https://cran.mirror.ac.za
Update? (Yes/no/cancel) Y
tidyr :
 Version 1.1.0 installed in /Library/Frameworks/R.framework/Versions/4.0/Resources/library 
 Version 1.1.1 available at https://cran.mirror.ac.za
Update? (Yes/no/cancel) Y
vctrs :
 Version 0.3.1 installed in /Library/Frameworks/R.framework/Versions/4.0/Resources/library 
 Version 0.3.2 available at https://cran.mirror.ac.za
Update? (Yes/no/cancel) Y
also installing the dependency ‘cpp11’

trying URL 'https://cran.mirror.ac.za/bin/macosx/contrib/4.0/cpp11_0.2.1.tgz'
Content type 'application/octet-stream' length 191339 bytes (186 KB)
==================================================
downloaded 186 KB

trying URL 'https://cran.mirror.ac.za/bin/macosx/contrib/4.0/data.table_1.13.0.tgz'
Content type 'application/octet-stream' length 2306488 bytes (2.2 MB)
==================================================
downloaded 2.2 MB

trying URL 'https://cran.mirror.ac.za/bin/macosx/contrib/4.0/deldir_0.1-28.tgz'
Content type 'application/octet-stream' length 273467 bytes (267 KB)
==================================================
downloaded 267 KB

trying URL 'https://cran.mirror.ac.za/bin/macosx/contrib/4.0/dplyr_1.0.1.tgz'
Content type 'application/octet-stream' length 1215793 bytes (1.2 MB)
==================================================
downloaded 1.2 MB

trying URL 'https://cran.mirror.ac.za/bin/macosx/contrib/4.0/epiR_1.0-15.tgz'
Content type 'application/octet-stream' length 847731 bytes (827 KB)
==================================================
downloaded 827 KB

trying URL 'https://cran.mirror.ac.za/bin/macosx/contrib/4.0/expm_0.999-5.tgz'
Content type 'application/octet-stream' length 237118 bytes (231 KB)
==================================================
downloaded 231 KB

trying URL 'https://cran.mirror.ac.za/bin/macosx/contrib/4.0/httr_1.4.2.tgz'
Content type 'application/octet-stream' length 498155 bytes (486 KB)
==================================================
downloaded 486 KB

trying URL 'https://cran.mirror.ac.za/bin/macosx/contrib/4.0/jsonlite_1.7.0.tgz'
Content type 'application/octet-stream' length 1121831 bytes (1.1 MB)
==================================================
downloaded 1.1 MB

trying URL 'https://cran.mirror.ac.za/bin/macosx/contrib/4.0/openssl_1.4.2.tgz'
Content type 'application/octet-stream' length 2687704 bytes (2.6 MB)
==================================================
downloaded 2.6 MB

trying URL 'https://cran.mirror.ac.za/bin/macosx/contrib/4.0/pillar_1.4.6.tgz'
Content type 'application/octet-stream' length 176431 bytes (172 KB)
==================================================
downloaded 172 KB

trying URL 'https://cran.mirror.ac.za/bin/macosx/contrib/4.0/pkgbuild_1.1.0.tgz'
Content type 'application/octet-stream' length 139362 bytes (136 KB)
==================================================
downloaded 136 KB

trying URL 'https://cran.mirror.ac.za/bin/macosx/contrib/4.0/processx_3.4.3.tgz'
Content type 'application/octet-stream' length 278450 bytes (271 KB)
==================================================
downloaded 271 KB

trying URL 'https://cran.mirror.ac.za/bin/macosx/contrib/4.0/ps_1.3.4.tgz'
Content type 'application/octet-stream' length 217609 bytes (212 KB)
==================================================
downloaded 212 KB

trying URL 'https://cran.mirror.ac.za/bin/macosx/contrib/4.0/raster_3.3-13.tgz'
Content type 'application/octet-stream' length 4229389 bytes (4.0 MB)
==================================================
downloaded 4.0 MB

trying URL 'https://cran.mirror.ac.za/bin/macosx/contrib/4.0/Rcpp_1.0.5.tgz'
Content type 'application/octet-stream' length 3215939 bytes (3.1 MB)
==================================================
downloaded 3.1 MB

trying URL 'https://cran.mirror.ac.za/bin/macosx/contrib/4.0/RcppArmadillo_0.9.900.2.0.tgz'
Content type 'application/octet-stream' length 1874697 bytes (1.8 MB)
==================================================
downloaded 1.8 MB

trying URL 'https://cran.mirror.ac.za/bin/macosx/contrib/4.0/rgdal_1.5-16.tgz'
Content type 'application/octet-stream' length 83941522 bytes (80.1 MB)
==================================================
downloaded 80.1 MB

trying URL 'https://cran.mirror.ac.za/bin/macosx/contrib/4.0/rlang_0.4.7.tgz'
Content type 'application/octet-stream' length 1210897 bytes (1.2 MB)
==================================================
downloaded 1.2 MB

trying URL 'https://cran.mirror.ac.za/bin/macosx/contrib/4.0/survival_3.2-3.tgz'
Content type 'application/octet-stream' length 7917007 bytes (7.6 MB)
==================================================
downloaded 7.6 MB

trying URL 'https://cran.mirror.ac.za/bin/macosx/contrib/4.0/sys_3.4.tgz'
Content type 'application/octet-stream' length 47291 bytes (46 KB)
==================================================
downloaded 46 KB

trying URL 'https://cran.mirror.ac.za/bin/macosx/contrib/4.0/tibble_3.0.3.tgz'
Content type 'application/octet-stream' length 394303 bytes (385 KB)
==================================================
downloaded 385 KB

trying URL 'https://cran.mirror.ac.za/bin/macosx/contrib/4.0/tidyr_1.1.1.tgz'
Content type 'application/octet-stream' length 928021 bytes (906 KB)
==================================================
downloaded 906 KB

trying URL 'https://cran.mirror.ac.za/bin/macosx/contrib/4.0/vctrs_0.3.2.tgz'
Content type 'application/octet-stream' length 1269066 bytes (1.2 MB)
==================================================
downloaded 1.2 MB


The downloaded binary packages are in
	/var/folders/cw/fhw1sm6j3s12t551gkm02qc80000gn/T//RtmpJ7gCOz/downloaded_packages
> install.packages(ggpubr)
Error in install.packages : object 'ggpubr' not found
> install.packages('ggpubr')
trying URL 'https://cran.mirror.ac.za/bin/macosx/contrib/4.0/ggpubr_0.4.0.tgz'
Content type 'application/octet-stream' length 1904641 bytes (1.8 MB)
==================================================
downloaded 1.8 MB


The downloaded binary packages are in
	/var/folders/cw/fhw1sm6j3s12t551gkm02qc80000gn/T//RtmpJ7gCOz/downloaded_packages
> library(ggpubr)
Loading required package: ggplot2
Error: package or namespace load failed for ‘ggpubr’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘zip’
> install.packages('zip')

  There is a binary version available but the source version is later:
    binary source needs_compilation
zip  2.0.4  2.1.0              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) Y
installing the source package ‘zip’

trying URL 'https://cran.mirror.ac.za/src/contrib/zip_2.1.0.tar.gz'
Content type 'application/octet-stream' length 112796 bytes (110 KB)
==================================================
downloaded 110 KB

* installing *source* package ‘zip’ ...
** package ‘zip’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘zip’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/zip’
Warning in install.packages :
  installation of package ‘zip’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/cw/fhw1sm6j3s12t551gkm02qc80000gn/T/RtmpJ7gCOz/downloaded_packages’
> library(ggpubr)
Error: package or namespace load failed for ‘ggpubr’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘zip’

**Comment by CJkirk105** [comment]
Hey Kassambara, 
I'm trying to install ggpubr, but getting this message if you could please assist:

`> if(!require(devtools)) install.packages("devtools")
> devtools::install_github("kassambara/ggpubr", dependencies = TRUE, INSTALL_opts = '--no-lock')
Downloading GitHub repo kassambara/ggpubr@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                              
2: CRAN packages only               
3: None                             
4: backports (1.1.7 -> 1.1.8) [CRAN]

Enter one or more numbers, or an empty line to skip updates:1
backports (1.1.7 -> 1.1.8) [CRAN]
Installing 1 packages: backports

  There is a binary version available but the source version is later:
          binary source needs_compilation
backports  1.1.7  1.1.8              TRUE

installing the source package ‘backports’

trying URL 'https://cran.ma.imperial.ac.uk/src/contrib/backports_1.1.8.tar.gz'
Content type 'application/x-gzip' length 18047 bytes (17 KB)
downloaded 17 KB

* installing *source* package 'backports' ...
** package 'backports' successfully unpacked and MD5 sums checked
ERROR: cannot remove earlier installation, is it in use?
* removing 'H:/R/R-4.0.2/library/backports'
Error: Failed to install 'ggpubr' from GitHub:
  (converted from warning) installation of package ‘backports’ had non-zero exit status`
