### ISSUE TITLE
Problem with "habillage" in fviz_mca_ind

### ISSUE THREAD

**Issue by DValour** [kassambara/factoextra#7]
Hi,

I tried this code:
fviz_mca_ind(res.mca, habillage=explain, addEllipses=TRUE, ellipse.level=0.95)+theme_minimal()

and I get this error:
Error in fviz_mca_ind(res.mca, habillage = explain) : could not find function ".scale_ca"

this happens while I installed factoextra_1.0.3.9000

Any idea about the problem?
Thanks.

**Comment by kassambara** [comment]
bug fixed now. Please let me know if it works.
Thank you!

**Comment by DValour** [comment]
Hi,

Thank you for your answer.
There was another modification in the new package.
How do I remove this strange labeling of arrows to come back to classical one?*

Thank you

[cid:image001.png@01D185EA.6AD5C110]

De : Alboukadel KASSAMBARA [mailto:notifications@github.com]
Envoyé : jeudi 24 mars 2016 14:29
À : kassambara/factoextra
Cc : VALOUR Damien * SOLADIS
Objet : Re: [factoextra] Problem with "habillage" in fviz_mca_ind (#7)


bug fixed now. Please let me know if it works.
Thank you!

**Comment by kassambara** [comment]
Hi,

could you please provide again the plot. It's not visible on github page.

Thank you!

**Comment by DValour** [comment]
Hi, in the function fviz_pca_var the label of the variable name seems to be jittered by default in the new version of factoextra. How can I come back to a normal labelling of arrows?

Thanks!

**Comment by kassambara** [comment]
--> Please, make sure that you have the latest version, which can be installed directly from CRAN or from GitHub:

```{r}
install.packages("factoextra")
```
   
   
--> Compute PCA and visualize variables
   
```{r}
library(factoextra)
res.pca <- prcomp(USArrests,  scale = TRUE)
fviz_pca_var(res.pca)
```
   
![rplot](https://cloud.githubusercontent.com/assets/3313355/15186555/ca7b4f82-179d-11e6-83f3-ad0e10f5742e.png)

Normally, there is no jittering by default. Could you, please, post the plot you obtained?

Best,
A.
