### ISSUE TITLE
fviz_dend() uses wrong tree when we force k on HCPC() 

### ISSUE THREAD

**Issue by scoavoux** [kassambara/factoextra#76]
For various reasons, one might want to cut a tree at a different level than the one automatically picked by HCPC with argument `nb.clust = -1`. In that case, the dendrogram should show the selected number of clusters.

Currently, however, `fviz_dend()` will show the "optimal" number of clusters even when we selected otherwise. MWE:

~~~r
library(FactoMineR)
library(factoextra)
data(iris)
res.pca <- PCA(iris[,1:4], graph=FALSE)
hc <- HCPC(res.pca, nb.clust=-1, graph=FALSE)
hc$call$t$nb.clust
## "Optimal" pick: three clusters. They are correctly plotted
fviz_dend(hc)

## Let's say I want five
hc <- HCPC(res.pca, nb.clust=5, graph=FALSE)

## Still plotting three clusters instead of five
fviz_dend(hc)

## even when specifying k
fviz_dend(hc, k = 5)
~~~

Could we fix this? I see two options:

First option:

fviz_dend currently uses this to determine k:

~~~r
  if (inherits(x, "HCPC")) {
    k <- x$call$t$nb.clust
    x <- x$call$t$tree
  }
~~~

We should rather use the actual number of clusters, something like:

~~~r
  if (inherits(x, "HCPC")) {
    k <- length(levels(x$data.clust$clust))
    x <- x$call$t$tree
  }
~~~

Second option

Allow for the k argument in fviz_dend to override `x$call$t$nb.clust`. That way, `fviz_dend(hc)` would  still plot the optimal tree while `fviz_dend(hc, k = 5)` would plot the chosen one.

~~~r
  if (inherits(x, "HCPC")) {
    if(!is.null(k)){
      k <- x$call$t$nb.clust
    }
    x <- x$call$t$tree
  }
~~~

I feel like the first option is better, though: why would we want to plot by default a dendrogram with different clusters than the ones we manually picked?

**Comment by kassambara** [comment]
Hi, 

This has been already fixed in the developmental version of factoextra.

You can install it using `devtools::Install_github("kassambara/factoextra")`

Thanks
