### ISSUE TITLE
fviz: problems with plotting to a file from within a function

### ISSUE THREAD

**Issue by balwierz** [kassambara/factoextra#86]
The problem ocurrs only when I am calling fviz_pca_var from within a function.
Exactly the same code pasted into R interpreter works well.
I have not observed this behaviour with other plotting function. No idea if this is fviz, output graphic device or ggplot problem...

Description:
For an obscure reason pdf and svg files are corrupted and png files are not created at all, when fviz_pca_var is being called from within a function.

Steps to reproduce.
create and execute this file with Rscript --vanilla
```r
testFviz = function()
{
	require(factoextra)
	mat = matrix(1:4, nrow=2)
	pc = princomp(mat)
	pdf("testFviz.pdf")
	factoextra::fviz_pca_var(pc)
	dev.off()
}
testFviz()
```

There will be "testFviz.pdf" created but corrupted. If you change png to svg the same problem will ocurr. When you change it to png, not even an empty png file will be created!

Now remove function brackets and rerun:
```r
require(factoextra)
mat = matrix(1:4, nrow=2)
pc = princomp(mat)
pdf("testFviz.pdf")
factoextra::fviz_pca_var(pc)
dev.off()
```
And it is all fine! I have no idea why.
Also if you replace in the original function `factoextra::fviz_pca_var(pc)` with `plot(1)`  it will also work.
It is not because of margin size etc.

```
R version 3.5.2 (2018-12-20)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux buster/sid

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.3.5.so

locale:
 [1] LC_CTYPE=en_DK.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_DK.UTF-8        LC_COLLATE=en_DK.UTF-8    
 [5] LC_MONETARY=en_DK.UTF-8    LC_MESSAGES=en_DK.UTF-8   
 [7] LC_PAPER=en_DK.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_DK.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] factoextra_1.0.5 ggplot2_3.1.0   

loaded via a namespace (and not attached):
 [1] ggrepel_0.8.0    Rcpp_1.0.1       ggpubr_0.2       withr_2.1.2     
 [5] crayon_1.3.4     dplyr_0.8.0.1    assertthat_0.2.0 grid_3.5.2      
 [9] plyr_1.8.4       R6_2.4.0         gtable_0.2.0     magrittr_1.5    
[13] scales_1.0.0     pillar_1.3.1     rlang_0.3.1      lazyeval_0.2.2  
[17] glue_1.3.1       purrr_0.3.2      munsell_0.5.0    compiler_3.5.2  
[21] pkgconfig_2.0.2  colorspace_1.4-1 tidyselect_0.2.5 tibble_2.1.1    

```

**Comment by kassambara** [comment]
Hi @balwierz,

This is a ggplot problem.

Kindly use the function print() to always make sure that the plot will be printed onto the devices (pdf/png/...)


Your function should look like this:

```r
testFviz = function()
{
	require(factoextra)
	mat = matrix(1:4, nrow=2)
	pc = princomp(mat)
	pdf("testFviz.pdf")
	print(factoextra::fviz_pca_var(pc))
	dev.off()
}
```

**Comment by balwierz** [comment]
Thanks kassambara,

It is a very nasty bug/feature of ggplot. Especially for users who have never heard, or used ggplot and just want to plot a bunch of PCAs.
Would it hurt to add `print` statement somewhere at the end of your plotting function? So that fviz would become loop+function-safe?

**Comment by kassambara** [comment]
If we print automatically the plot, then some users that want to customize the plot can't do so.

**Comment by dsuissa** [comment]
Hi, I have the same issue for other types of plots, even when using "print"  between the definition of pdf/jpg/... and dev.off(), nothing is plotted ...
 Have you found other ways to overcome this issue ? 
Thanks in advance.
