### ISSUE TITLE
what is the default for the FUN=hclust

### ISSUE THREAD

**Issue by marieleyse** [kassambara/factoextra#91]
Hi, 

I'm trying to determine the number of clusters to use on a Kendall correlation matrix.

If I use this script:
fviz_nbclust(mydata.cor, hcut, method = "wss")+
  geom_vline(xintercept = 3, linetype = 2)+
  labs(subtitle = "Elbow method")

or
set.seed(123)
fviz_nbclust(mydata.cor, hcut, nstart = 25,  method = "gap_stat", nboot = 500)+
  labs(subtitle = "Gap statistic method")

what is the default hierarchical clustering method? 

Thank you very much

**Comment by kassambara** [comment]
Hi, by default, `hc_method = "ward.D2", hc_metric = "euclidean"`, see the documentation of `hcut()`

**Comment by marieleyse** [comment]
thank you so much
