### ISSUE TITLE
Issue with the dimensions of standardisation

### ISSUE THREAD

**Issue by agnesolin** [kassambara/factoextra#92]
Hi,

I think I have potentially found an issue with get_dist (but not 100% sure).

If stand = T, then the line "x <- scale(x)" will be run. The function scale standardises over columns. However, if I understand correctly x rather has the data by rows (later correlations are calculated on t(x), which would make sense if data are by rows rather than by columns). I.e. the scaling is done over the wrong dimension, which impacts the correlations calculated.

Again, I may be wrong about this but thought I would raise it in case it is an issue.

Thanks for making this package!

**Comment by kassambara** [comment]
Hi,
scaling is applied on the data as it is.

Globally,  `get_dist()`,  like many others factoextra functions, assumes that rows are individuals and columns are variables. So, scaling is performed on variables and dissimilarity matrix is computed between individuals (like in the R base function `dist()`)

**Comment by agnesolin** [comment]
Oh right, I am using the data for correlations between time series (in which case standardisation does not make a difference) which I guess is different from how most people use the function. Thanks for the response!
