### ISSUE TITLE
some letters over the legend points in PCA

### ISSUE THREAD

**Issue by VladStoianH** [kassambara/factoextra#97]
I used a code based on the tutorial for PCA, but when plotting the PCA on every point in the legend appear teh letter "a". 

This is the code and a picture with the graph. I also want to remove the background from point in the legend. Thank you

fviz_pca_biplot(res.pca, repel = TRUE,
                col.ind = alldata$Replicates,
                addEllipses = TRUE,
                ellipse.type = "confidence",
                col.var = "black", # Variables color
                legend.title = "Groups", 
                palette=c("#f1eef6", "#d0d1e6", "#a6bddb", "#74a9cf", "#3690c0", "#0570b0", "#034e7b"))+
        theme_minimal()+scale_shape_manual(values=c(19,20,21,22,23,24,25,26))

![the a in the legend](https://user-images.githubusercontent.com/47420604/61874272-a8452a80-aef0-11e9-868f-4666481f8d45.png)

**Comment by kassambara** [comment]
to hide text in the legend, specify the option `show.legend.text = FALSE`

**Comment by VladStoianH** [comment]
Many thanks, It is working now. The graph look perfect. Your package offer a lot of PCA solutions to explore my data.

**Comment by wzthhm** [comment]
> to hide text in the legend, specify the option `show.legend.text = FALSE`

Why can't see "fviz_pca_xx" object as "gg" object?
When I used some function such as geom_text_repel, got an error " geom_text_repel requires the following missing aesthetics: label". But "fviz_pca_xx" has "label" aesthetics
Thanks,Pardon my ignorance,I'm a beginner.
